"""
GUI for SBS Param Dumper: export HTML/Markdown and edit autofill presets (JSON).

Parsing and output layout are controlled by per-field options (saved in gui_settings.json).

Requires Python 3 with tkinter.
"""

from __future__ import annotations

import json
import os
import platform
import queue
import subprocess
import sys
import threading
import tkinter as tk
from tkinter import filedialog, messagebox, scrolledtext, ttk
from typing import Any, cast

from autofill_preset import (
    AutofillPreset,
    default_input_rules,
    default_presets_dir,
    default_preset_path,
    empty_input_rule,
    ensure_presets_dir,
    legacy_inputs_dict_to_rules,
    list_preset_paths,
    normalize_input_rule,
)
from markdown_format import DEFAULT_MARKDOWN_FORMAT, merge_markdown_defaults
from HTMLDumper import HTMLDumper
from MarkdownDumper import MarkdownDumper
from sbs_dump_config import CategorySource, SBSDumpConfig
from SBSreader import SBSReader


def script_dir() -> str:
    return os.path.dirname(os.path.realpath(__file__))


SETTINGS_PATH = os.path.join(script_dir(), "gui_settings.json")

# (field name, checkbox label) for SBSDumpConfig boolean fields
DUMP_CFG_BOOL_FIELDS: list[tuple[str, str]] = [
    ("normalize_xml_category_names", "Normalize XML category names (Filter → Filters, …)"),
    ("remap_graph_tags", "Remap graph tags (Blur → Blurs, …)"),
    ("allow_graphs_without_tag", "Include graphs with an empty tag"),
    ("show_complexity_rating", "Show complexity rating"),
    ("hide_workflow_normal_params", "Hide workflow_type & normal_format parameters"),
    ("show_graph_tag_in_header", "Show graph tag in the location line (category/tag)"),
    (
        "check_tag_conflicts_for_output_layout",
        "Use flat output path when graphs disagree on tag",
    ),
    ("nest_output_subfolder_by_tag", "Nest output under a tag subfolder"),
]

# Hover help for “Parsing & output layout” (and related Export controls)
CATEGORY_SOURCE_TOOLTIPS = {
    "xml": (
        "Read each graph’s category from inside the .sbs XML (the package metadata). "
        "Use this when the file’s stored category is what you want for headings and folders."
    ),
    "folder": (
        "Ignore the XML category for categorization and derive a category from disk layout: "
        "the folder name two levels above the .sbs file, capitalized. "
        "Useful when your documentation tree is organized by folders, not by what’s in the XML."
    ),
}

DUMP_CFG_FIELD_TOOLTIPS: dict[str, str] = {
    "normalize_xml_category_names": (
        "When category comes from XML, rewrite internal values to the usual library-style names "
        "(e.g. Filter → Filters, Generator → Generators). "
        "Has no effect if category source is “Parent folder name.”"
    ),
    "remap_graph_tags": (
        "Rewrite tag strings from the XML into consistent names (e.g. Blur → Blurs, Noise → Noises). "
        "Turn off to keep tags exactly as stored in the file."
    ),
    "allow_graphs_without_tag": (
        "If off, graphs with an empty tag are skipped (with a console warning). "
        "If on, those graphs are still documented—needed for some packages where tags are missing on purpose."
    ),
    "show_complexity_rating": (
        "Adds a Simple / Intermediate / Complex line to each graph’s doc, estimated from how many "
        "parameters and inputs it has. This is generated by the dumper, not read from the .sbs."
    ),
    "hide_workflow_normal_params": (
        "Omits the parameters named workflow_type and normal_format from the written documentation. "
        "They are technical switches that are often redundant in prose docs."
    ),
    "show_graph_tag_in_header": (
        "The “In:” line shows Category/Tag. If off, only the category is shown—useful when tags are "
        "noisy or not meaningful for readers."
    ),
    "check_tag_conflicts_for_output_layout": (
        "When a single .sbs produces multiple graphs with different tags, enabling this detects the "
        "mismatch and writes files in the output root (flat) so nothing overwrites another file. "
        "If off, that tag conflict check is not applied to paths."
    ),
    "nest_output_subfolder_by_tag": (
        "If on (and the path is not flattened because of a conflict), files go under "
        "output/Category/Tag/. If off, they go under output/Category/ without an extra tag folder."
    ),
}

DUMP_CFG_PRESET_TOOLTIPS = {
    "defaults": (
        "Restore all parsing and layout options to the built-in defaults: category from XML, "
        "normalized names, tag remapping, tag subfolders, complexity line, etc."
    ),
    "folder_library": (
        "Apply a preset bundle: category from parent folders, no XML category/tag rewriting, "
        "include untagged graphs, flatter output paths, hide workflow/normal params, no complexity line. "
        "Matches the old folder-oriented export script."
    ),
}

EXPORT_OPTION_TOOLTIPS = {
    "html": "Write one .html file per processed package, using the autofill preset for missing blurbs.",
    "markdown": "Write one .md file per package using the Markdown templates from the same autofill preset.",
    "recursive": (
        "When the source is a folder, also search inside subfolders for .sbs files. "
        "When off, only files directly in that folder are used."
    ),
    "autofill_preset": (
        "JSON preset that supplies default parameter descriptions, channel intro text, input hints, "
        "and Markdown templates. Edit presets on the Presets / Markdown tabs."
    ),
    "autofill_refresh": "Reload the preset file list from the folder set on the Presets tab.",
    "source": "Path to one .sbs file or to a folder of .sbs files to process.",
    "browse_file": "Choose a single Substance .sbs package.",
    "browse_folder": "Choose a folder containing .sbs files (use the subfolder option below to go deeper).",
    "output": (
        "Directory where exported .html / .md files are written. "
        "Depending on layout options, subfolders for category (and tag) may be created inside."
    ),
    "browse_out": "Choose the output directory.",
    "run_export": "Run export in the background. Progress and errors appear in the log below.",
}


class ToolTip:
    """Small delayed hover popup (tk has no native tooltips)."""

    def __init__(self, widget: tk.Widget, text: str, delay_ms: int = 450) -> None:
        self.widget = widget
        self.text = (text or "").strip()
        self.delay_ms = delay_ms
        self._tip: tk.Toplevel | None = None
        self._after_id: str | None = None
        if self.text:
            widget.bind("<Enter>", self._schedule, add="+")
            widget.bind("<Leave>", self._hide, add="+")
            widget.bind("<ButtonPress>", self._hide, add="+")
            widget.bind("<Destroy>", self._on_destroy, add="+")

    def _on_destroy(self, _event=None) -> None:
        self._hide()

    def _cancel_scheduled(self) -> None:
        if self._after_id is not None:
            try:
                self.widget.after_cancel(self._after_id)
            except tk.TclError:
                pass
            self._after_id = None

    def _schedule(self, _event=None) -> None:
        self._cancel_scheduled()
        self._after_id = self.widget.after(self.delay_ms, self._show)

    def _show(self) -> None:
        self._after_id = None
        if self._tip is not None or not self.text:
            return
        try:
            if not self.widget.winfo_exists():
                return
        except tk.TclError:
            return
        x = self.widget.winfo_rootx() + 12
        y = self.widget.winfo_rooty() + self.widget.winfo_height() + 6
        root = self.widget.winfo_toplevel()
        tip = tk.Toplevel(root)
        self._tip = tip
        tip.wm_overrideredirect(True)
        try:
            tip.wm_attributes("-topmost", True)
        except tk.TclError:
            pass
        lbl = tk.Label(
            tip,
            text=self.text,
            justify=tk.LEFT,
            background="#ffffe0",
            foreground="#000000",
            relief=tk.SOLID,
            borderwidth=1,
            wraplength=420,
            font=("TkDefaultFont", 9),
        )
        lbl.pack(ipadx=8, ipady=6)
        tip.update_idletasks()
        # Keep on screen (rough)
        sw = tip.winfo_screenwidth()
        sh = tip.winfo_screenheight()
        tw = tip.winfo_width()
        th = tip.winfo_height()
        if x + tw > sw - 8:
            x = max(8, sw - tw - 8)
        if y + th > sh - 8:
            y = max(8, self.widget.winfo_rooty() - th - 8)
        tip.geometry(f"+{x}+{y}")

    def _hide(self, _event=None) -> None:
        self._cancel_scheduled()
        if self._tip is not None:
            try:
                self._tip.destroy()
            except tk.TclError:
                pass
            self._tip = None


def load_settings() -> dict:
    if os.path.isfile(SETTINGS_PATH):
        try:
            with open(SETTINGS_PATH, encoding="utf-8") as f:
                data = json.load(f)
            return data if isinstance(data, dict) else {}
        except (OSError, json.JSONDecodeError):
            pass
    return {}


def save_settings(**kwargs: object) -> None:
    data = load_settings()
    for key, value in kwargs.items():
        data[key] = value
    try:
        with open(SETTINGS_PATH, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
    except OSError:
        pass


def default_output_folder() -> str:
    sd = script_dir()
    candidate = os.path.join(os.path.dirname(sd), "Parameter Descriptions")
    if os.path.isdir(candidate):
        return candidate
    return sd


def collect_sbs_paths(root: str, recursive: bool) -> list[str]:
    root = os.path.normpath(root)
    paths: list[str] = []
    if not os.path.exists(root):
        return paths
    if os.path.isfile(root):
        if root.lower().endswith(".sbs"):
            return [root]
        return paths
    if not os.path.isdir(root):
        return paths
    if recursive:
        for dirpath, _, filenames in os.walk(root):
            for fn in filenames:
                if fn.lower().endswith(".sbs"):
                    paths.append(os.path.join(dirpath, fn))
    else:
        for fn in os.listdir(root):
            full = os.path.join(root, fn)
            if os.path.isfile(full) and fn.lower().endswith(".sbs"):
                paths.append(full)
    return sorted(paths)


def open_path_in_os(path: str) -> None:
    """Open a file or folder in the default app / file manager (best effort)."""
    path = os.path.normpath(os.path.abspath(path))
    if not os.path.exists(path):
        return
    try:
        if platform.system() == "Windows":
            os.startfile(path)  # type: ignore[attr-defined]
        elif sys.platform == "darwin":
            subprocess.run(["open", path], check=False)
        else:
            subprocess.run(["xdg-open", path], check=False)
    except OSError:
        pass


def parse_sbs(path: str, config: SBSDumpConfig):
    reader = SBSReader(path, config=config)
    return reader.Parse()


def run_export(
    paths: list[str],
    out_dir: str,
    config: SBSDumpConfig,
    write_html: bool,
    write_md: bool,
    autofill_path: str,
    log,
) -> tuple[int, int, dict[str, Any]]:
    ok = 0
    err = 0
    html_paths: list[str] = []
    md_paths: list[str] = []
    out_abs = os.path.abspath(out_dir)
    try:
        autofill = AutofillPreset.from_file(autofill_path)
    except Exception as e:
        log(f"Preset error ({autofill_path}): {e}")
        autofill = AutofillPreset.load_default()
    for path in paths:
        log(f"Processing: {path}")
        try:
            desc = parse_sbs(path, config)
        except Exception as e:
            log(f"  Error reading XML: {e}")
            err += 1
            continue
        if desc is None:
            log("  Skipped (could not parse).")
            err += 1
            continue
        graph_count = len(getattr(desc, "graphs", []) or [])
        if graph_count == 0:
            log(
                "  Skipped (0 graphs matched current filters). "
                "Try enabling 'Include graphs with an empty tag'."
            )
            err += 1
            continue
        try:
            if write_html:
                hd = HTMLDumper(p_writefolder=out_dir, p_config=config, p_autofill=autofill)
                html = hd.BuildHTML(desc)
                p = hd.WriteToFile(html)
                if p:
                    html_paths.append(p)
                elif html:
                    log("  Warning: HTML was built but not written (deprecated/empty filename?).")
                else:
                    log("  Warning: HTML build returned empty output.")
            if write_md:
                md = MarkdownDumper(p_writefolder=out_dir, p_config=config, p_autofill=autofill)
                text = md.BuildMarkdown(desc)
                p2 = md.WriteToFile(text)
                if p2:
                    md_paths.append(p2)
                elif text:
                    log("  Warning: Markdown was built but not written (deprecated/empty filename?).")
                else:
                    log("  Warning: Markdown build returned empty output.")
        except Exception as e:
            log(f"  Error writing output: {e}")
            err += 1
            continue
        ok += 1
        log("  Done.")
    artifacts: dict[str, Any] = {
        "out_dir": out_abs,
        "html_paths": html_paths,
        "md_paths": md_paths,
        "source_count": len(paths),
        "ok_count": ok,
    }
    return ok, err, artifacts


class PresetsTab(ttk.Frame):
    def __init__(
        self,
        parent,
        on_presets_changed,
        selected_preset_var: tk.StringVar | None = None,
        get_dump_config_dict=None,
        apply_dump_config_dict=None,
    ) -> None:
        super().__init__(parent)
        self._on_presets_changed = on_presets_changed
        self._get_dump_config_dict = get_dump_config_dict
        self._apply_dump_config_dict = apply_dump_config_dict
        self._current_file: str | None = None
        self._edit: dict = {}
        self._list_keys: list[str] = []
        self._loading_listbox = False
        self._active_param_key: str | None = None
        self._loading_rules_listbox = False
        self._active_rule_index: int | None = None

        r = 0
        ttk.Label(self, text="Presets folder (add .json files here):").grid(
            row=r, column=0, columnspan=2, sticky="w"
        )
        r += 1
        self.dir_var = tk.StringVar(value=default_presets_dir())
        ttk.Entry(self, textvariable=self.dir_var, width=52).grid(
            row=r, column=0, sticky="ew", padx=(0, 8)
        )
        ttk.Button(self, text="Browse…", command=self._browse_dir).grid(row=r, column=1, sticky="e")
        r += 1

        row = ttk.Frame(self)
        row.grid(row=r, column=0, columnspan=2, sticky="ew", pady=(10, 0))
        ttk.Label(row, text="Preset file:").pack(side=tk.LEFT)
        self.file_combo = ttk.Combobox(
            row,
            width=36,
            state="readonly",
            textvariable=selected_preset_var,
        )
        self.file_combo.pack(side=tk.LEFT, padx=(8, 0))
        self.file_combo.bind("<<ComboboxSelected>>", self._on_file_selected)
        ttk.Button(row, text="Refresh list", command=self.refresh_file_list).pack(side=tk.LEFT, padx=(8, 0))
        ttk.Button(row, text="New preset…", command=self._new_preset).pack(side=tk.LEFT, padx=(8, 0))
        ttk.Button(row, text="Save", command=self._save).pack(side=tk.LEFT, padx=(8, 0))
        ttk.Button(row, text="Save as…", command=self._save_as).pack(side=tk.LEFT, padx=(8, 0))
        ttk.Button(row, text="Reload from disk", command=self._reload).pack(side=tk.LEFT, padx=(8, 0))
        r += 1

        ttk.Label(self, text="Parameter labels (exact match to node parameter name):").grid(
            row=r, column=0, columnspan=2, sticky="w", pady=(12, 4)
        )
        r += 1
        mid = ttk.Panedwindow(self, orient=tk.HORIZONTAL)
        mid.grid(row=r, column=0, columnspan=2, sticky="nsew")
        self.rowconfigure(r, weight=1)

        left = ttk.Frame(mid, padding=(0, 0, 8, 0))
        self.keys_listbox = tk.Listbox(left, height=16, exportselection=False)
        self.keys_listbox.pack(fill=tk.BOTH, expand=True)
        self.keys_listbox.bind("<<ListboxSelect>>", self._on_key_select)

        add_row = ttk.Frame(left)
        add_row.pack(fill=tk.X, pady=(6, 0))
        self.new_key_var = tk.StringVar()
        ttk.Entry(add_row, textvariable=self.new_key_var, width=22).pack(side=tk.LEFT)
        ttk.Button(add_row, text="Add", command=self._add_key).pack(side=tk.LEFT, padx=(6, 0))
        ttk.Button(add_row, text="Remove", command=self._remove_key).pack(side=tk.LEFT, padx=(6, 0))

        right = ttk.Frame(mid)
        ttk.Label(right, text="Description for selected parameter:").pack(anchor="w")
        self.desc_text = scrolledtext.ScrolledText(right, height=14, width=40, wrap=tk.WORD)
        self.desc_text.pack(fill=tk.BOTH, expand=True, pady=(4, 0))
        ttk.Label(
            right,
            text="Tip: use @OtherParameterName to reuse another line’s text (same as in JSON).",
            wraplength=320,
        ).pack(anchor="w", pady=(6, 0))

        mid.add(left, weight=1)
        mid.add(right, weight=2)

        r += 1
        meta = ttk.LabelFrame(self, text="Preset details", padding=8)
        meta.grid(row=r, column=0, columnspan=2, sticky="ew", pady=(12, 0))
        meta.columnconfigure(1, weight=1)
        mr = 0
        ttk.Label(meta, text="Display name:").grid(row=mr, column=0, sticky="nw", padx=(0, 8))
        self.display_name_var = tk.StringVar()
        ttk.Entry(meta, textvariable=self.display_name_var).grid(row=mr, column=1, sticky="ew")
        mr += 1
        ttk.Label(meta, text="Blending intensity template:").grid(row=mr, column=0, sticky="nw", padx=(0, 8), pady=(6, 0))
        self.blending_var = tk.StringVar()
        ttk.Entry(meta, textvariable=self.blending_var).grid(row=mr, column=1, sticky="ew", pady=(6, 0))
        ttk.Label(meta, text="(for “Something Intensity” params — use {key} for the prefix.)", font=("TkDefaultFont", 8)).grid(
            row=mr + 1, column=1, sticky="w"
        )
        mr += 2
        ttk.Label(meta, text="Channels group intro:").grid(row=mr, column=0, sticky="nw", padx=(0, 8), pady=(6, 0))
        self.channels_text = scrolledtext.ScrolledText(meta, height=3, wrap=tk.WORD)
        self.channels_text.grid(row=mr, column=1, sticky="ew", pady=(6, 0))
        mr += 1

        irf = ttk.LabelFrame(
            self,
            text="Input slot rules (top → bottom; first match wins — compares to each input’s name)",
            padding=8,
        )
        irf.grid(row=r + 1, column=0, columnspan=2, sticky="nsew", pady=(10, 0))
        irf.columnconfigure(1, weight=1)
        irf.rowconfigure(0, weight=1)

        ir_left = ttk.Frame(irf)
        ir_left.grid(row=0, column=0, sticky="nsew", padx=(0, 8))
        ir_left.rowconfigure(0, weight=1)
        self.rules_listbox = tk.Listbox(ir_left, height=9, width=28, exportselection=False)
        self.rules_listbox.grid(row=0, column=0, sticky="nsew")
        self.rules_listbox.bind("<<ListboxSelect>>", self._on_rule_select)
        rbtn = ttk.Frame(ir_left)
        rbtn.grid(row=1, column=0, sticky="ew", pady=(6, 0))
        ttk.Button(rbtn, text="Add rule", command=self._add_rule).pack(side=tk.LEFT)
        ttk.Button(rbtn, text="Remove", command=self._remove_rule).pack(side=tk.LEFT, padx=(6, 0))
        ttk.Button(rbtn, text="Up", command=self._rule_move_up).pack(side=tk.LEFT, padx=(6, 0))
        ttk.Button(rbtn, text="Down", command=self._rule_move_down).pack(side=tk.LEFT, padx=(6, 0))

        ir_right = ttk.Frame(irf)
        ir_right.grid(row=0, column=1, sticky="nsew")
        ir_right.columnconfigure(1, weight=1)
        rr = 0
        ttk.Label(ir_right, text="Rule id (label only):").grid(row=rr, column=0, sticky="w", padx=(0, 8))
        self.rule_id_var = tk.StringVar()
        ttk.Entry(ir_right, textvariable=self.rule_id_var, width=24).grid(row=rr, column=1, sticky="ew")
        rr += 1
        ttk.Label(ir_right, text="Match type:").grid(row=rr, column=0, sticky="nw", padx=(0, 8), pady=(6, 0))
        self.rule_match_type = ttk.Combobox(
            ir_right,
            width=22,
            state="readonly",
            values=("contains", "equals", "equals_any", "all_contain", "regex"),
        )
        self.rule_match_type.grid(row=rr, column=1, sticky="w", pady=(6, 0))
        rr += 1
        ttk.Label(ir_right, text="Match value (contains / equals / regex):").grid(
            row=rr, column=0, sticky="nw", padx=(0, 8), pady=(4, 0)
        )
        self.rule_match_value_var = tk.StringVar()
        ttk.Entry(ir_right, textvariable=self.rule_match_value_var).grid(row=rr, column=1, sticky="ew", pady=(4, 0))
        rr += 1
        ttk.Label(ir_right, text="Match list (equals_any / all_contain — one per line):").grid(
            row=rr, column=0, sticky="nw", padx=(0, 8), pady=(4, 0)
        )
        self.rule_match_values_text = scrolledtext.ScrolledText(ir_right, height=3, wrap=tk.NONE)
        self.rule_match_values_text.grid(row=rr, column=1, sticky="ew", pady=(4, 0))
        rr += 1
        ttk.Label(ir_right, text="Description text:").grid(row=rr, column=0, sticky="nw", padx=(0, 8), pady=(4, 0))
        self.rule_desc_text = scrolledtext.ScrolledText(ir_right, height=4, wrap=tk.WORD)
        self.rule_desc_text.grid(row=rr, column=1, sticky="ew", pady=(4, 0))
        rr += 1
        self.rule_append_toggle = tk.BooleanVar(value=False)
        ttk.Checkbutton(
            ir_right,
            text="Append boolean-toggle hint (looks up a Boolean parameter on the graph)",
            variable=self.rule_append_toggle,
        ).grid(row=rr, column=0, columnspan=2, sticky="w", pady=(6, 0))
        rr += 1
        ttk.Label(ir_right, text="Boolean param names (comma-separated):").grid(
            row=rr, column=0, sticky="nw", padx=(0, 8), pady=(2, 0)
        )
        self.rule_toggle_names = tk.StringVar(value="Mask, Use Mask, Alpha Blending")
        ttk.Entry(ir_right, textvariable=self.rule_toggle_names).grid(row=rr, column=1, sticky="ew", pady=(2, 0))
        rr += 1
        ttk.Label(ir_right, text="Toggle template ({mask_param}):").grid(
            row=rr, column=0, sticky="nw", padx=(0, 8), pady=(2, 0)
        )
        self.rule_toggle_template = tk.StringVar(
            value=' Can be toggled with the "{mask_param}" parameter.'
        )
        ttk.Entry(ir_right, textvariable=self.rule_toggle_template).grid(row=rr, column=1, sticky="ew", pady=(2, 0))
        rr += 1
        self.rule_append_pattern = tk.BooleanVar(value=False)
        ttk.Checkbutton(
            ir_right,
            text="Append pattern-dropdown hint (finds a dropdown param name on the graph)",
            variable=self.rule_append_pattern,
        ).grid(row=rr, column=0, columnspan=2, sticky="w", pady=(6, 0))
        rr += 1
        ttk.Label(ir_right, text="Pattern param names (comma-separated):").grid(
            row=rr, column=0, sticky="nw", padx=(0, 8), pady=(2, 0)
        )
        self.rule_pattern_names = tk.StringVar(value="Pattern Type, Pattern")
        ttk.Entry(ir_right, textvariable=self.rule_pattern_names).grid(row=rr, column=1, sticky="ew", pady=(2, 0))
        rr += 1
        ttk.Label(ir_right, text="Pattern suffix ({pattern_param}):").grid(
            row=rr, column=0, sticky="nw", padx=(0, 8), pady=(2, 0)
        )
        self.rule_pattern_suffix = tk.StringVar(
            value=', used when the "{pattern_param}" parameter is set to "Image Input"'
        )
        ttk.Entry(ir_right, textvariable=self.rule_pattern_suffix).grid(row=rr, column=1, sticky="ew", pady=(2, 0))
        rr += 1
        self.rule_append_period = tk.BooleanVar(value=False)
        ttk.Checkbutton(
            ir_right,
            text='Append "." at end (after pattern suffix)',
            variable=self.rule_append_period,
        ).grid(row=rr, column=0, columnspan=2, sticky="w", pady=(4, 0))

        self.columnconfigure(0, weight=1)

    def _parse_comma_names(self, s: str) -> list[str]:
        return [x.strip() for x in s.split(",") if x.strip()]

    def _flush_active_param_key(self) -> None:
        if self._active_param_key is None:
            return
        params = self._edit.setdefault("parameters", {})
        if self._active_param_key in params or self._active_param_key in self._list_keys:
            params[self._active_param_key] = self.desc_text.get("1.0", "end").rstrip("\n")

    def _flush_active_rule(self) -> None:
        if self._active_rule_index is None:
            return
        rules = self._edit.setdefault("input_rules", [])
        if 0 <= self._active_rule_index < len(rules):
            rules[self._active_rule_index] = self._read_rule_from_form()

    def _read_rule_from_form(self) -> dict:
        mt = (self.rule_match_type.get() or "contains").strip().lower()
        raw_lines = [
            ln.strip() for ln in self.rule_match_values_text.get("1.0", "end").splitlines() if ln.strip()
        ]
        return normalize_input_rule(
            {
                "id": self.rule_id_var.get().strip() or "rule",
                "match_type": mt,
                "match_value": self.rule_match_value_var.get(),
                "match_values": raw_lines if mt in ("equals_any", "all_contain") else [],
                "text": self.rule_desc_text.get("1.0", "end").rstrip("\n"),
                "append_boolean_toggle": self.rule_append_toggle.get(),
                "toggle_lookup_param_names": self._parse_comma_names(self.rule_toggle_names.get())
                or ["Mask", "Use Mask", "Alpha Blending"],
                "toggle_template": self.rule_toggle_template.get(),
                "append_pattern_dropdown": self.rule_append_pattern.get(),
                "pattern_lookup_param_names": self._parse_comma_names(self.rule_pattern_names.get())
                or ["Pattern Type", "Pattern"],
                "pattern_suffix_template": self.rule_pattern_suffix.get(),
                "append_period": self.rule_append_period.get(),
            }
        )

    def _load_rule_into_form(self, rule: dict) -> None:
        r = normalize_input_rule(dict(rule))
        self.rule_id_var.set(r["id"])
        self.rule_match_type.set(r["match_type"])
        self.rule_match_value_var.set(r["match_value"])
        self.rule_match_values_text.delete("1.0", tk.END)
        self.rule_match_values_text.insert("1.0", "\n".join(r["match_values"]))
        self.rule_desc_text.delete("1.0", tk.END)
        self.rule_desc_text.insert("1.0", r["text"])
        self.rule_append_toggle.set(r["append_boolean_toggle"])
        self.rule_toggle_names.set(", ".join(r["toggle_lookup_param_names"]))
        self.rule_toggle_template.set(r["toggle_template"])
        self.rule_append_pattern.set(r["append_pattern_dropdown"])
        self.rule_pattern_names.set(", ".join(r["pattern_lookup_param_names"]))
        self.rule_pattern_suffix.set(r["pattern_suffix_template"])
        self.rule_append_period.set(r["append_period"])

    def _clear_rule_form(self) -> None:
        self.rule_id_var.set("new_rule")
        self.rule_match_type.set("contains")
        self.rule_match_value_var.set("")
        self.rule_match_values_text.delete("1.0", tk.END)
        self.rule_desc_text.delete("1.0", tk.END)
        self.rule_append_toggle.set(False)
        self.rule_toggle_names.set("Mask, Use Mask, Alpha Blending")
        self.rule_toggle_template.set(' Can be toggled with the "{mask_param}" parameter.')
        self.rule_append_pattern.set(False)
        self.rule_pattern_names.set("Pattern Type, Pattern")
        self.rule_pattern_suffix.set(', used when the "{pattern_param}" parameter is set to "Image Input"')
        self.rule_append_period.set(False)

    def _refresh_rules_listbox(self, select_index: int | None = None) -> None:
        rules = self._edit.setdefault("input_rules", [])
        self._loading_rules_listbox = True
        self.rules_listbox.delete(0, tk.END)
        for rule in rules:
            rid = rule.get("id", "?")
            mt = rule.get("match_type", "")
            self.rules_listbox.insert(tk.END, f"{rid} — {mt}")
        self._loading_rules_listbox = False
        if not rules:
            self._active_rule_index = None
            self._clear_rule_form()
            return
        idx = 0 if select_index is None else select_index
        idx = max(0, min(idx, len(rules) - 1))
        self.rules_listbox.selection_clear(0, tk.END)
        self.rules_listbox.selection_set(idx)
        self.rules_listbox.see(idx)
        self._active_rule_index = idx
        self._load_rule_into_form(rules[idx])

    def _on_rule_select(self, _evt=None) -> None:
        if self._loading_rules_listbox:
            return
        self._flush_active_rule()
        sel = self.rules_listbox.curselection()
        if not sel:
            self._active_rule_index = None
            return
        idx = sel[0]
        rules = self._edit.setdefault("input_rules", [])
        if idx >= len(rules):
            return
        self._active_rule_index = idx
        self._load_rule_into_form(rules[idx])

    def _add_rule(self) -> None:
        self._flush_active_rule()
        rules = self._edit.setdefault("input_rules", [])
        rules.append(normalize_input_rule(empty_input_rule()))
        self._refresh_rules_listbox(select_index=len(rules) - 1)

    def _remove_rule(self) -> None:
        self._flush_active_rule()
        sel = self.rules_listbox.curselection()
        if not sel:
            return
        idx = sel[0]
        rules = self._edit.setdefault("input_rules", [])
        if 0 <= idx < len(rules):
            rules.pop(idx)
        self._active_rule_index = None
        self._refresh_rules_listbox(select_index=min(idx, len(rules) - 1) if rules else None)

    def _rule_move_up(self) -> None:
        self._flush_active_rule()
        sel = self.rules_listbox.curselection()
        if not sel or sel[0] == 0:
            return
        rules = self._edit.setdefault("input_rules", [])
        i = sel[0]
        rules[i - 1], rules[i] = rules[i], rules[i - 1]
        self._refresh_rules_listbox(select_index=i - 1)

    def _rule_move_down(self) -> None:
        self._flush_active_rule()
        sel = self.rules_listbox.curselection()
        rules = self._edit.setdefault("input_rules", [])
        if not sel or sel[0] >= len(rules) - 1:
            return
        i = sel[0]
        rules[i + 1], rules[i] = rules[i], rules[i + 1]
        self._refresh_rules_listbox(select_index=i + 1)

    def _ensure_input_rules(self) -> None:
        ir = self._edit.get("input_rules")
        if isinstance(ir, list):
            self._edit["input_rules"] = [
                normalize_input_rule(dict(x)) for x in ir if isinstance(x, dict)
            ]
            return
        leg = self._edit.get("inputs")
        if isinstance(leg, dict) and leg:
            self._edit["input_rules"] = [
                normalize_input_rule(x) for x in legacy_inputs_dict_to_rules(leg)
            ]
        else:
            self._edit["input_rules"] = [normalize_input_rule(x) for x in default_input_rules()]

    def _prepare_edit_for_save(self) -> None:
        self._flush_active_param_key()
        self._flush_active_rule()
        self._edit["display_name"] = self.display_name_var.get().strip() or "Preset"
        self._edit["blending_intensity_template"] = self.blending_var.get().strip()
        self._edit["channels_intro"] = self.channels_text.get("1.0", "end").rstrip("\n")
        rules = self._edit.setdefault("input_rules", [])
        self._edit["input_rules"] = [normalize_input_rule(dict(r)) for r in rules]
        self._edit.pop("inputs", None)
        if callable(self._get_dump_config_dict):
            try:
                self._edit["dump_config"] = self._get_dump_config_dict()
            except Exception:
                pass

    def flush_all_pending(self) -> None:
        self._flush_active_param_key()
        self._flush_active_rule()

    def set_presets_dir(self, path: str) -> None:
        self.dir_var.set(path)
        self.refresh_file_list()

    def _browse_dir(self) -> None:
        path = filedialog.askdirectory(title="Folder containing preset .json files")
        if path:
            self.dir_var.set(path)
            save_settings(presets_directory=path)
            self.refresh_file_list()
            self._on_presets_changed()

    def refresh_file_list(self) -> None:
        d = self.dir_var.get().strip()
        ensure_presets_dir()
        if not os.path.isdir(d):
            try:
                os.makedirs(d, exist_ok=True)
            except OSError:
                pass
        paths = list_preset_paths(d) if os.path.isdir(d) else []
        names = [os.path.basename(p) for p in paths]
        self.file_combo["values"] = names
        if names:
            current_name = self.file_combo.get().strip()
            current_file_name = os.path.basename(self._current_file) if self._current_file else ""
            prefer = "designer_default.json"
            if current_name in names:
                self.file_combo.set(current_name)
            elif current_file_name in names:
                self.file_combo.set(current_file_name)
            elif prefer in names:
                self.file_combo.set(prefer)
            else:
                self.file_combo.set(names[0])
            self._load_path(os.path.join(d, self.file_combo.get()))
        else:
            self.file_combo.set("")
            self._blank_editor()

    def _on_file_selected(self, _evt=None) -> None:
        name = self.file_combo.get()
        if not name:
            return
        path = os.path.join(self.dir_var.get().strip(), name)
        self._load_path(path)

    def _load_path(self, path: str) -> None:
        if not os.path.isfile(path):
            self._blank_editor()
            return
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            messagebox.showerror("Preset", f"Could not read JSON:\n{e}")
            return
        if not isinstance(data, dict):
            messagebox.showerror("Preset", "File must contain a JSON object.")
            return
        self._current_file = path
        self._edit = data
        self._edit.setdefault("version", 1)
        self._edit.setdefault("display_name", os.path.splitext(os.path.basename(path))[0])
        self._edit.setdefault("parameters", {})
        self._edit.setdefault("blending_intensity_template", "Blending strength of the {key}.")
        self._edit.setdefault("channels_intro", "")
        if not isinstance(self._edit["parameters"], dict):
            self._edit["parameters"] = {}
        self._ensure_input_rules()
        dc = self._edit.get("dump_config")
        if not isinstance(dc, dict):
            self._edit["dump_config"] = SBSDumpConfig().to_dict()
        if callable(self._apply_dump_config_dict):
            try:
                self._apply_dump_config_dict(self._edit.get("dump_config"))
            except Exception:
                pass

        self.display_name_var.set(str(self._edit.get("display_name", "")))
        self.blending_var.set(str(self._edit.get("blending_intensity_template", "")))
        self.channels_text.delete("1.0", tk.END)
        self.channels_text.insert("1.0", str(self._edit.get("channels_intro", "")))

        self._list_keys = list(self._edit["parameters"].keys())
        self._loading_listbox = True
        self.keys_listbox.delete(0, tk.END)
        for k in self._list_keys:
            self.keys_listbox.insert(tk.END, k)
        self._loading_listbox = False
        self.desc_text.delete("1.0", tk.END)
        self._active_param_key = None
        if self._list_keys:
            self.keys_listbox.selection_set(0)
            self._active_param_key = self._list_keys[0]
            self._show_key(self._active_param_key)
        self._refresh_rules_listbox(select_index=0 if self._edit["input_rules"] else None)
        self._on_presets_changed()

    def _blank_editor(self) -> None:
        self._current_file = None
        self._edit = {
            "version": 1,
            "display_name": "New preset",
            "parameters": {},
            "blending_intensity_template": "Blending strength of the {key}.",
            "channels_intro": "",
            "input_rules": [],
            "markdown": merge_markdown_defaults(None),
            "dump_config": SBSDumpConfig().to_dict(),
        }
        if callable(self._apply_dump_config_dict):
            try:
                self._apply_dump_config_dict(self._edit.get("dump_config"))
            except Exception:
                pass
        self.display_name_var.set("New preset")
        self.blending_var.set(self._edit["blending_intensity_template"])
        self.channels_text.delete("1.0", tk.END)
        self._list_keys = []
        self.keys_listbox.delete(0, tk.END)
        self.desc_text.delete("1.0", tk.END)
        self._active_param_key = None
        self._refresh_rules_listbox(select_index=None)

    def _show_key(self, key: str) -> None:
        self.desc_text.delete("1.0", tk.END)
        params = self._edit.setdefault("parameters", {})
        self.desc_text.insert("1.0", str(params.get(key, "")))

    def _on_key_select(self, _evt=None) -> None:
        if self._loading_listbox:
            return
        self._flush_active_param_key()
        sel = self.keys_listbox.curselection()
        if not sel:
            self._active_param_key = None
            return
        key = self._list_keys[sel[0]]
        self._active_param_key = key
        self._show_key(key)

    def _add_key(self) -> None:
        self._flush_active_param_key()
        name = self.new_key_var.get().strip()
        if not name:
            messagebox.showinfo("Add parameter", "Enter a parameter label first.")
            return
        params = self._edit.setdefault("parameters", {})
        if name not in self._list_keys:
            self._list_keys.append(name)
            self.keys_listbox.insert(tk.END, name)
        params.setdefault(name, "")
        self.keys_listbox.selection_clear(0, tk.END)
        idx = self._list_keys.index(name)
        self.keys_listbox.selection_set(idx)
        self.keys_listbox.see(idx)
        self._active_param_key = name
        self._show_key(name)
        self.new_key_var.set("")

    def _remove_key(self) -> None:
        self._flush_active_param_key()
        sel = self.keys_listbox.curselection()
        if not sel:
            return
        idx = sel[0]
        key = self._list_keys.pop(idx)
        self._edit.setdefault("parameters", {}).pop(key, None)
        self.keys_listbox.delete(idx)
        self.desc_text.delete("1.0", tk.END)
        if self._list_keys:
            new_i = min(idx, len(self._list_keys) - 1)
            self.keys_listbox.selection_set(new_i)
            self._active_param_key = self._list_keys[new_i]
            self._show_key(self._active_param_key)
        else:
            self._active_param_key = None

    def _save(self) -> None:
        self._prepare_edit_for_save()
        if not self._current_file:
            self._save_as()
            return
        path = self._current_file
        try:
            with open(path, "w", encoding="utf-8") as f:
                json.dump(self._edit, f, indent=2, ensure_ascii=False)
        except OSError as e:
            messagebox.showerror("Save", str(e))
            return
        messagebox.showinfo("Saved", f"Wrote:\n{path}")
        self._on_presets_changed()

    def _save_as(self) -> None:
        self._prepare_edit_for_save()
        d = self.dir_var.get().strip() or default_presets_dir()
        os.makedirs(d, exist_ok=True)
        path = filedialog.asksaveasfilename(
            title="Save preset as",
            initialdir=d,
            defaultextension=".json",
            filetypes=[("JSON preset", "*.json"), ("All files", "*.*")],
        )
        if not path:
            return
        self._current_file = path
        try:
            with open(path, "w", encoding="utf-8") as f:
                json.dump(self._edit, f, indent=2, ensure_ascii=False)
        except OSError as e:
            messagebox.showerror("Save", str(e))
            return
        self.dir_var.set(os.path.dirname(path))
        save_settings(presets_directory=self.dir_var.get())
        self.refresh_file_list()
        base = os.path.basename(path)
        if base in self.file_combo["values"]:
            self.file_combo.set(base)
            self._load_path(path)
        messagebox.showinfo("Saved", f"Wrote:\n{path}")
        self._on_presets_changed()

    def _reload(self) -> None:
        if self._current_file and os.path.isfile(self._current_file):
            self._load_path(self._current_file)
        else:
            self.refresh_file_list()

    def _new_preset(self) -> None:
        self._blank_editor()
        self._current_file = None
        messagebox.showinfo(
            "New preset",
            "Edit entries, then use Save as… to write a new .json file in your presets folder.",
        )


MARKDOWN_UI_GROUPS: list[tuple[str, list[tuple[str, str]]]] = [
    (
        "Graph header",
        [
            ("graph_title", "Title line — placeholder: {title}"),
            ("location_line", "Location line — placeholder: {location}"),
            ("graph_description", "Graph / package description — placeholder: {description}"),
        ],
    ),
    (
        "Complexity (when enabled in Export layout)",
        [
            ("complexity_line", "Wrapper for the resolved label — placeholder: {complexity}"),
            ("complexity_simple", "Label when complexity is Simple (no placeholders)"),
            ("complexity_intermediate", "Label when complexity is Intermediate"),
            ("complexity_complex", "Label when complexity is Complex"),
            ("complexity_unknown", "Label when complexity is unknown"),
        ],
    ),
    (
        "Section headings",
        [
            ("inputs_heading", "Heading before the inputs list (include trailing newline if you want a blank line)"),
            ("parameters_heading", "Heading before parameters (include trailing newline if needed)"),
        ],
    ),
    (
        "Inputs list",
        [
            ("input_item", "Single input entry — placeholders: {name}, {type}, {body}"),
            ("input_body", "Input body formatting — placeholders: {help} (and {body})"),
        ],
    ),
    (
        "Parameters list",
        [
            ("param_group_item", "Parameter group name row — placeholder: {group}"),
            ("param_row", "Single parameter entry — placeholders: {name}, {range}, {body}"),
            ("nested_indent", "Spaces prepended to nested list lines (usually 4 spaces)"),
            ("channels_bullet", "Channels intro bullet — placeholder: {text}"),
        ],
    ),
    (
        "No parameters",
        [
            ("no_params", "When a graph has no parameters — placeholder: {generator_note}"),
            ("no_params_generator_note", "Appended into {generator_note} for category “Generators:” only"),
        ],
    ),
]


class MarkdownFormatTab(ttk.Frame):
    """Edit the `markdown` section of the selected preset JSON (same file as Presets tab)."""

    def __init__(self, parent, app: "SBSParamDumperApp") -> None:
        super().__init__(parent, padding=8)
        self.app = app
        self._widgets: dict[str, tk.Widget] = {}

        ttk.Label(
            self,
            text="These templates control Markdown export only. They are stored in the preset file under “markdown”. "
            "Use the same preset on the Export tab. Literal braces: {{ and }}.",
            wraplength=680,
        ).pack(anchor="w", pady=(0, 8))

        toolbar = ttk.Frame(self)
        toolbar.pack(fill=tk.X, pady=(0, 8))
        ttk.Label(toolbar, text="Preset file:").pack(side=tk.LEFT)
        self.preset_combo = ttk.Combobox(
            toolbar,
            width=36,
            state="readonly",
            textvariable=self.app.selected_preset_var,
        )
        self.preset_combo.pack(side=tk.LEFT, padx=(8, 0))
        self.preset_combo.bind("<<ComboboxSelected>>", lambda _e: self.reload_from_file(quiet=True))
        ttk.Button(toolbar, text="Refresh list", command=self._refresh_preset_list).pack(side=tk.LEFT, padx=(8, 0))
        ttk.Button(toolbar, text="New preset…", command=self._new_preset).pack(side=tk.LEFT, padx=(8, 0))
        ttk.Button(toolbar, text="Save", command=self._save_full_preset).pack(side=tk.LEFT, padx=(8, 0))
        ttk.Button(toolbar, text="Save as…", command=self._save_full_preset_as).pack(side=tk.LEFT, padx=(8, 0))
        ttk.Button(toolbar, text="Reload from disk", command=self._reload_full_preset).pack(side=tk.LEFT, padx=(8, 0))

        canvas_wrap = ttk.Frame(self)
        canvas_wrap.pack(fill=tk.BOTH, expand=True)
        canvas = tk.Canvas(canvas_wrap, highlightthickness=0)
        scroll = ttk.Scrollbar(canvas_wrap, orient=tk.VERTICAL, command=canvas.yview)
        canvas.configure(yscrollcommand=scroll.set)
        inner = ttk.Frame(canvas)
        win_id = canvas.create_window((0, 0), window=inner, anchor="nw")

        def _on_inner_configure(_event=None) -> None:
            canvas.configure(scrollregion=canvas.bbox("all"))

        def _on_canvas_configure(event) -> None:
            canvas.itemconfigure(win_id, width=event.width)

        inner.bind("<Configure>", _on_inner_configure)
        canvas.bind("<Configure>", _on_canvas_configure)

        canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scroll.pack(side=tk.RIGHT, fill=tk.Y)

        for group_title, fields in MARKDOWN_UI_GROUPS:
            lf = ttk.LabelFrame(inner, text=group_title, padding=8)
            lf.pack(fill=tk.X, pady=(0, 10))
            lf.columnconfigure(1, weight=1)
            gr = 0
            for key, desc in fields:
                ttk.Label(lf, text=desc, wraplength=200).grid(row=gr, column=0, sticky="nw", padx=(0, 8), pady=4)
                if key == "nested_indent":
                    e = ttk.Entry(lf, width=72)
                    e.grid(row=gr, column=1, sticky="ew", pady=4)
                    self._widgets[key] = e
                else:
                    tx = scrolledtext.ScrolledText(lf, height=2, width=72, wrap=tk.WORD, font=("TkFixedFont", 9))
                    tx.grid(row=gr, column=1, sticky="ew", pady=4)
                    self._widgets[key] = tx
                gr += 1

        self.reload_from_file(quiet=True)

    def _preset_json_path(self) -> str | None:
        pt = self.app.presets_tab
        d = pt.dir_var.get().strip()
        n = self.app.selected_preset_var.get().strip()
        if d and n:
            p = os.path.join(d, n)
            if os.path.isfile(p):
                return p
        return None

    def _refresh_preset_list(self) -> None:
        self.app.presets_tab.refresh_file_list()
        self.app._refresh_export_preset_combo()
        self.reload_from_file(quiet=True)

    def _ensure_selected_preset_loaded_in_editor(self) -> bool:
        path = self._preset_json_path()
        if not path:
            return False
        cur = self.app.presets_tab._current_file
        if not cur or os.path.abspath(cur) != os.path.abspath(path):
            self.app.presets_tab._load_path(path)
        return True

    def _new_preset(self) -> None:
        self.app.presets_tab._new_preset()
        self.reset_defaults()
        self.app._refresh_export_preset_combo()

    def _save_full_preset(self) -> None:
        if not self._ensure_selected_preset_loaded_in_editor():
            messagebox.showwarning("Markdown", "Choose a preset file first.")
            return
        self.app.presets_tab.flush_all_pending()
        self.app.presets_tab._edit["markdown"] = self._gather_dict()
        self.app.presets_tab._save()
        self.reload_from_file(quiet=True)
        self.app._refresh_export_preset_combo()

    def _save_full_preset_as(self) -> None:
        if not self._ensure_selected_preset_loaded_in_editor():
            # Create a new in-memory preset first if nothing is selected.
            self.app.presets_tab._blank_editor()
        self.app.presets_tab.flush_all_pending()
        self.app.presets_tab._edit["markdown"] = self._gather_dict()
        self.app.presets_tab._save_as()
        self.reload_from_file(quiet=True)
        self.app._refresh_export_preset_combo()

    def _reload_full_preset(self) -> None:
        self.app.presets_tab._reload()
        self.reload_from_file(quiet=True)

    def _set_widget_text(self, key: str, value: str) -> None:
        w = self._widgets[key]
        if isinstance(w, ttk.Entry):
            w.delete(0, tk.END)
            w.insert(0, value)
        else:
            w.delete("1.0", tk.END)
            w.insert("1.0", value)

    def _get_widget_text(self, key: str) -> str:
        w = self._widgets[key]
        if isinstance(w, ttk.Entry):
            return w.get().strip("\n")
        return w.get("1.0", "end").rstrip("\n")

    def _apply_dict(self, data: dict[str, str]) -> None:
        for key in self._widgets:
            self._set_widget_text(key, data.get(key, DEFAULT_MARKDOWN_FORMAT.get(key, "")))

    def reload_from_file(self, quiet: bool = False) -> None:
        path = self._preset_json_path()
        if not path:
            if not quiet:
                messagebox.showwarning("Markdown", "Choose a preset file on the Presets tab first.")
            self.reset_defaults()
            return
        try:
            with open(path, encoding="utf-8") as f:
                root = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            messagebox.showerror("Markdown", str(e))
            return
        md = root.get("markdown") if isinstance(root, dict) else None
        merged = merge_markdown_defaults(md if isinstance(md, dict) else None)
        self._apply_dict(merged)

    def reset_defaults(self) -> None:
        self._apply_dict(merge_markdown_defaults(None))

    def _gather_dict(self) -> dict[str, str]:
        return {key: self._get_widget_text(key) for key in self._widgets}

    def save_to_file(self) -> None:
        self.app.presets_tab.flush_all_pending()
        path = self._preset_json_path()
        if not path:
            messagebox.showwarning("Markdown", "Choose a preset file on the Presets tab first.")
            return
        try:
            with open(path, encoding="utf-8") as f:
                root = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            messagebox.showerror("Markdown", str(e))
            return
        if not isinstance(root, dict):
            messagebox.showerror("Markdown", "Preset file must be a JSON object.")
            return
        md = self._gather_dict()
        root["markdown"] = md
        try:
            with open(path, "w", encoding="utf-8") as f:
                json.dump(root, f, indent=2, ensure_ascii=False)
        except OSError as e:
            messagebox.showerror("Markdown", str(e))
            return
        ap = os.path.abspath(path)
        if self.app.presets_tab._current_file and os.path.abspath(self.app.presets_tab._current_file) == ap:
            self.app.presets_tab._edit["markdown"] = md
        messagebox.showinfo("Markdown", f"Updated markdown section in:\n{path}")
        self.app._refresh_export_preset_combo()


class SBSParamDumperApp(tk.Tk):
    def __init__(self) -> None:
        super().__init__()
        self.title("SBS Param Dumper")
        self.minsize(720, 560)
        self._log_queue: queue.Queue[tuple[str, Any]] = queue.Queue()
        self._worker: threading.Thread | None = None
        self._preview_job: str | None = None
        self._preview_ready = False
        self._last_preview_html = ""
        self._preview_backend = "text"
        self._html_frame: Any = None
        self.selected_preset_var = tk.StringVar(value="")
        self._preset_sync_in_progress = False
        self._pending_dump_cfg_from_preset: SBSDumpConfig | None = None

        settings = load_settings()
        preset_dir = settings.get("presets_directory") or default_presets_dir()
        ensure_presets_dir()

        self.rowconfigure(0, weight=1)
        self.columnconfigure(0, weight=1)

        nb = ttk.Notebook(self)
        nb.grid(row=0, column=0, sticky="nsew", padx=0, pady=0)

        export_frame = ttk.Frame(nb, padding=12)
        nb.add(export_frame, text="Export")
        export_frame.columnconfigure(1, weight=1)

        self.presets_tab = PresetsTab(
            nb,
            on_presets_changed=self._refresh_export_preset_combo,
            selected_preset_var=self.selected_preset_var,
            get_dump_config_dict=lambda: self._dump_config_from_ui().to_dict(),
            apply_dump_config_dict=self._apply_dump_config_from_preset_dict,
        )
        nb.add(self.presets_tab, text="Presets")
        self.presets_tab.set_presets_dir(preset_dir)

        self.markdown_tab = MarkdownFormatTab(nb, self)
        nb.add(self.markdown_tab, text="Markdown")

        r = 0
        src_hdr = ttk.Label(export_frame, text="Source (.sbs file or folder):")
        src_hdr.grid(row=r, column=0, columnspan=3, sticky="w")
        ToolTip(src_hdr, EXPORT_OPTION_TOOLTIPS["source"])
        r += 1
        self.source_var = tk.StringVar()
        src_entry = ttk.Entry(export_frame, textvariable=self.source_var, width=56)
        src_entry.grid(row=r, column=0, columnspan=2, sticky="ew", padx=(0, 8))
        ToolTip(src_entry, EXPORT_OPTION_TOOLTIPS["source"])
        btn_browse_file = ttk.Button(export_frame, text="Browse file…", command=self._browse_file)
        btn_browse_file.grid(row=r, column=2, sticky="e")
        ToolTip(btn_browse_file, EXPORT_OPTION_TOOLTIPS["browse_file"])
        r += 1
        btn_browse_folder = ttk.Button(export_frame, text="Browse folder…", command=self._browse_folder)
        btn_browse_folder.grid(row=r, column=2, sticky="e")
        ToolTip(btn_browse_folder, EXPORT_OPTION_TOOLTIPS["browse_folder"])

        r += 1
        out_hdr = ttk.Label(export_frame, text="Output folder:")
        out_hdr.grid(row=r, column=0, columnspan=3, sticky="w", pady=(12, 0))
        ToolTip(out_hdr, EXPORT_OPTION_TOOLTIPS["output"])
        r += 1
        self.out_var = tk.StringVar(value=default_output_folder())
        out_entry = ttk.Entry(export_frame, textvariable=self.out_var, width=56)
        out_entry.grid(row=r, column=0, columnspan=2, sticky="ew", padx=(0, 8))
        ToolTip(out_entry, EXPORT_OPTION_TOOLTIPS["output"])
        btn_browse_out = ttk.Button(export_frame, text="Browse…", command=self._browse_out)
        btn_browse_out.grid(row=r, column=2, sticky="e")
        ToolTip(btn_browse_out, EXPORT_OPTION_TOOLTIPS["browse_out"])

        r += 1
        cfg_frame = ttk.LabelFrame(export_frame, text="Parsing & output layout", padding=8)
        cfg_frame.grid(row=r, column=0, columnspan=3, sticky="ew", pady=(12, 0))
        cfg_frame.columnconfigure(0, weight=1)

        cat_inner = ttk.Frame(cfg_frame)
        cat_inner.grid(row=0, column=0, sticky="w")
        cat_lbl = ttk.Label(cat_inner, text="Category source:")
        cat_lbl.pack(side=tk.LEFT)
        ToolTip(
            cat_lbl,
            "Where the exporter gets the graph category for headings and output folders. "
            "Hover each radio button for the two strategies.",
        )
        self._category_src_var = tk.StringVar(value="xml")
        rb_xml = ttk.Radiobutton(
            cat_inner, text="Graph XML", variable=self._category_src_var, value="xml"
        )
        rb_xml.pack(side=tk.LEFT, padx=(8, 0))
        ToolTip(rb_xml, CATEGORY_SOURCE_TOOLTIPS["xml"])
        rb_folder = ttk.Radiobutton(
            cat_inner,
            text="Parent folder name",
            variable=self._category_src_var,
            value="folder",
        )
        rb_folder.pack(side=tk.LEFT, padx=(8, 0))
        ToolTip(rb_folder, CATEGORY_SOURCE_TOOLTIPS["folder"])

        self._dump_bool_vars: dict[str, tk.BooleanVar] = {}
        br = 1
        for field, blabel in DUMP_CFG_BOOL_FIELDS:
            self._dump_bool_vars[field] = tk.BooleanVar(value=False)
            cb = ttk.Checkbutton(cfg_frame, text=blabel, variable=self._dump_bool_vars[field])
            cb.grid(row=br, column=0, sticky="w", pady=(2, 0))
            ToolTip(cb, DUMP_CFG_FIELD_TOOLTIPS.get(field, ""))
            br += 1

        preset_btns = ttk.Frame(cfg_frame)
        preset_btns.grid(row=br, column=0, sticky="w", pady=(10, 0))
        btn_dump_defaults = ttk.Button(
            preset_btns, text="Reset defaults", command=self._reset_dump_config_defaults
        )
        btn_dump_defaults.pack(side=tk.LEFT)
        ToolTip(btn_dump_defaults, DUMP_CFG_PRESET_TOOLTIPS["defaults"])
        btn_dump_folder = ttk.Button(
            preset_btns,
            text="Folder library preset",
            command=self._apply_folder_library_dump_preset,
        )
        btn_dump_folder.pack(side=tk.LEFT, padx=(8, 0))
        ToolTip(btn_dump_folder, DUMP_CFG_PRESET_TOOLTIPS["folder_library"])

        initial_dump = self._pending_dump_cfg_from_preset
        if initial_dump is None:
            initial_dump = SBSDumpConfig.from_dict(
                settings.get("dump_config") if isinstance(settings.get("dump_config"), dict) else None
            )
        self._apply_dump_config_to_ui(initial_dump)
        self._pending_dump_cfg_from_preset = None

        r += 1
        af_lbl = ttk.Label(export_frame, text="Main preset:")
        af_lbl.grid(row=r, column=0, sticky="w", pady=(12, 0))
        ToolTip(af_lbl, EXPORT_OPTION_TOOLTIPS["autofill_preset"])
        row_pf = ttk.Frame(export_frame)
        row_pf.grid(row=r, column=1, columnspan=2, sticky="ew", pady=(12, 0))
        self.export_preset_combo = ttk.Combobox(
            row_pf,
            width=44,
            state="readonly",
            textvariable=self.selected_preset_var,
        )
        self.export_preset_combo.pack(side=tk.LEFT)
        ToolTip(self.export_preset_combo, EXPORT_OPTION_TOOLTIPS["autofill_preset"])
        btn_preset_refresh = ttk.Button(row_pf, text="Refresh", command=self._refresh_export_preset_combo)
        btn_preset_refresh.pack(side=tk.LEFT, padx=(8, 0))
        ToolTip(btn_preset_refresh, EXPORT_OPTION_TOOLTIPS["autofill_refresh"])
        self._preset_dir_for_export = preset_dir
        self._refresh_export_preset_combo()
        self.selected_preset_var.trace_add("write", self._on_global_preset_changed)

        r += 1
        opt_frame = ttk.LabelFrame(export_frame, text="Export", padding=8)
        opt_frame.grid(row=r, column=0, columnspan=3, sticky="ew", pady=(12, 0))
        self.html_var = tk.BooleanVar(value=False)
        self.md_var = tk.BooleanVar(value=True)
        self.recursive_var = tk.BooleanVar(value=True)
        cb_html = ttk.Checkbutton(opt_frame, text="Write HTML (.html)", variable=self.html_var)
        cb_html.grid(row=0, column=0, sticky="w")
        ToolTip(cb_html, EXPORT_OPTION_TOOLTIPS["html"])
        cb_md = ttk.Checkbutton(opt_frame, text="Write Markdown (.md)", variable=self.md_var)
        cb_md.grid(row=0, column=1, sticky="w", padx=(24, 0))
        ToolTip(cb_md, EXPORT_OPTION_TOOLTIPS["markdown"])
        cb_rec = ttk.Checkbutton(
            opt_frame,
            text="Include subfolders when source is a folder",
            variable=self.recursive_var,
        )
        cb_rec.grid(row=1, column=0, columnspan=2, sticky="w", pady=(6, 0))
        ToolTip(cb_rec, EXPORT_OPTION_TOOLTIPS["recursive"])

        r += 1
        btn_frame = ttk.Frame(export_frame)
        btn_frame.grid(row=r, column=0, columnspan=3, pady=(12, 0))
        self.run_btn = ttk.Button(btn_frame, text="Run export", command=self._on_run)
        self.run_btn.pack(side=tk.LEFT)
        ToolTip(self.run_btn, EXPORT_OPTION_TOOLTIPS["run_export"])
        ttk.Label(
            btn_frame,
            text="Log and live preview share the row below (drag the divider).",
        ).pack(side=tk.LEFT, padx=(16, 0))

        r += 1
        paned = ttk.Panedwindow(export_frame, orient=tk.HORIZONTAL)
        paned.grid(row=r, column=0, columnspan=3, sticky="nsew", pady=(12, 0))
        export_frame.rowconfigure(r, weight=1)

        log_pane = ttk.Frame(paned, padding=(0, 0, 8, 0))
        preview_pane = ttk.Frame(paned, padding=(8, 0, 0, 0))
        paned.add(log_pane, weight=1)
        paned.add(preview_pane, weight=2)

        self._export_links_frame = ttk.Frame(log_pane)
        self._export_links_frame.pack(fill=tk.X, anchor="w", pady=(0, 6))

        ttk.Label(log_pane, text="Log:").pack(anchor="w")
        self.log_widget = scrolledtext.ScrolledText(log_pane, height=10, wrap=tk.WORD, state=tk.DISABLED)
        self.log_widget.pack(fill=tk.BOTH, expand=True)

        prev_hdr = ttk.Frame(preview_pane)
        prev_hdr.pack(fill=tk.X, pady=(0, 6))
        ttk.Label(prev_hdr, text="Live preview:").pack(side=tk.LEFT)
        self.preview_format_var = tk.StringVar(value="markdown")
        self.preview_render_var = tk.StringVar(value="rendered")
        ttk.Radiobutton(
            prev_hdr,
            text="HTML",
            variable=self.preview_format_var,
            value="html",
            command=self._schedule_live_preview,
        ).pack(side=tk.LEFT, padx=(12, 0))
        ttk.Radiobutton(
            prev_hdr,
            text="Markdown",
            variable=self.preview_format_var,
            value="markdown",
            command=self._schedule_live_preview,
        ).pack(side=tk.LEFT, padx=(8, 0))
        ttk.Radiobutton(
            prev_hdr,
            text="Rendered",
            variable=self.preview_render_var,
            value="rendered",
            command=self._schedule_live_preview,
        ).pack(side=tk.LEFT, padx=(16, 0))
        ttk.Radiobutton(
            prev_hdr,
            text="Raw",
            variable=self.preview_render_var,
            value="raw",
            command=self._schedule_live_preview,
        ).pack(side=tk.LEFT, padx=(8, 0))
        ttk.Button(prev_hdr, text="Refresh now", command=self._run_live_preview).pack(side=tk.LEFT, padx=(12, 0))
        ttk.Button(prev_hdr, text="Open in window…", command=self._open_preview_window).pack(side=tk.LEFT, padx=(8, 0))

        self._preview_status_var = tk.StringVar(value="")
        ttk.Label(preview_pane, textvariable=self._preview_status_var, wraplength=420, font=("TkDefaultFont", 8)).pack(
            anchor="w", pady=(0, 4)
        )

        preview_host = ttk.Frame(preview_pane)
        preview_host.pack(fill=tk.BOTH, expand=True)
        try:
            from tkinterweb import HtmlFrame

            self._html_frame = HtmlFrame(preview_host, messages_enabled=False)
            self._html_frame.pack(fill=tk.BOTH, expand=True)
            self._preview_backend = "tkinterweb"
        except ImportError:
            self._html_frame = scrolledtext.ScrolledText(preview_host, height=14, wrap=tk.WORD, font=("Consolas", 9))
            self._html_frame.pack(fill=tk.BOTH, expand=True)
            self._preview_backend = "text"

        self._preview_ready = True
        self._wire_live_preview()
        self.after(600, self._schedule_live_preview)

        nb.bind("<<NotebookTabChanged>>", self._on_tab_changed)

        self.after(150, self._drain_log_queue)

    def _apply_dump_config_to_ui(self, cfg: SBSDumpConfig) -> None:
        self._category_src_var.set(cfg.category_source)
        for name, var in self._dump_bool_vars.items():
            var.set(getattr(cfg, name))

    def _dump_config_from_ui(self) -> SBSDumpConfig:
        raw = self._category_src_var.get()
        cs = cast(CategorySource, raw if raw in ("xml", "folder") else "xml")
        bools = {name: bool(var.get()) for name, var in self._dump_bool_vars.items()}
        return SBSDumpConfig(category_source=cs, **bools)

    def _reset_dump_config_defaults(self) -> None:
        self._apply_dump_config_to_ui(SBSDumpConfig())

    def _apply_folder_library_dump_preset(self) -> None:
        self._apply_dump_config_to_ui(SBSDumpConfig.folder_library_style())

    def _apply_dump_config_from_preset_dict(self, data: dict[str, Any] | None) -> None:
        cfg = SBSDumpConfig.from_dict(data if isinstance(data, dict) else None)
        if hasattr(self, "_category_src_var"):
            self._apply_dump_config_to_ui(cfg)
            if getattr(self, "_preview_ready", False):
                self._schedule_live_preview()
        else:
            self._pending_dump_cfg_from_preset = cfg

    def _on_tab_changed(self, _evt=None) -> None:
        try:
            self.presets_tab.flush_all_pending()
        except Exception:
            pass
        try:
            self.markdown_tab.reload_from_file(quiet=True)
        except Exception:
            pass
        self._schedule_live_preview()

    def _preview_mode(self) -> str:
        fmt = self.preview_format_var.get()
        rnd = self.preview_render_var.get()
        if fmt not in ("html", "markdown"):
            fmt = "markdown"
        if rnd not in ("rendered", "raw"):
            rnd = "rendered"
        return f"{fmt}_{rnd}"

    def _refresh_export_preset_combo(self) -> None:
        if not hasattr(self, "export_preset_combo"):
            return
        d = self.presets_tab.dir_var.get().strip() if hasattr(self, "presets_tab") else self._preset_dir_for_export
        self._preset_dir_for_export = d
        paths = list_preset_paths(d) if os.path.isdir(d) else []
        names = [os.path.basename(p) for p in paths]
        self.export_preset_combo["values"] = names
        if hasattr(self, "markdown_tab") and hasattr(self.markdown_tab, "preset_combo"):
            self.markdown_tab.preset_combo["values"] = names
        cur = self.selected_preset_var.get().strip()
        if names:
            if cur in names:
                self.selected_preset_var.set(cur)
            elif "designer_default.json" in names:
                self.selected_preset_var.set("designer_default.json")
            else:
                self.selected_preset_var.set(names[0])
        else:
            self.selected_preset_var.set("")
        if getattr(self, "_preview_ready", False):
            self._schedule_live_preview()

    def _on_global_preset_changed(self, *_args) -> None:
        if self._preset_sync_in_progress or not hasattr(self, "presets_tab"):
            return
        name = self.selected_preset_var.get().strip()
        d = self.presets_tab.dir_var.get().strip()
        if not name or not d:
            return
        path = os.path.join(d, name)
        if not os.path.isfile(path):
            return
        self._preset_sync_in_progress = True
        try:
            cur_abs = os.path.abspath(self.presets_tab._current_file) if self.presets_tab._current_file else ""
            next_abs = os.path.abspath(path)
            if cur_abs != next_abs:
                self.presets_tab._load_path(path)
            if hasattr(self, "markdown_tab"):
                self.markdown_tab.reload_from_file(quiet=True)
        finally:
            self._preset_sync_in_progress = False
        if getattr(self, "_preview_ready", False):
            self._schedule_live_preview()

    def _export_selected_preset_path(self) -> str:
        name = self.export_preset_combo.get()
        d = self.presets_tab.dir_var.get().strip()
        if name and d and os.path.isdir(d):
            full = os.path.join(d, name)
            if os.path.isfile(full):
                return full
        return default_preset_path()

    def _preview_sbs_path(self) -> str | None:
        src = self.source_var.get().strip()
        if not src:
            return None
        if os.path.isfile(src) and src.lower().endswith(".sbs"):
            return src
        if os.path.isdir(src):
            paths = collect_sbs_paths(src, self.recursive_var.get())
            return paths[0] if paths else None
        return None

    def _wire_live_preview(self) -> None:
        cb = lambda *_: self._schedule_live_preview()
        self.source_var.trace_add("write", cb)
        self.recursive_var.trace_add("write", cb)
        self._category_src_var.trace_add("write", cb)
        for v in self._dump_bool_vars.values():
            v.trace_add("write", cb)
        self.preview_format_var.trace_add("write", cb)
        self.preview_render_var.trace_add("write", cb)
        self.export_preset_combo.bind("<<ComboboxSelected>>", lambda _e: self._schedule_live_preview())

    def _schedule_live_preview(self) -> None:
        if not self._preview_ready:
            return
        jid = self._preview_job
        if jid is not None:
            try:
                self.after_cancel(jid)
            except Exception:
                pass
        self._preview_job = self.after(400, self._run_live_preview)

    def _run_live_preview(self) -> None:
        self._preview_job = None
        if not self._preview_ready:
            return
        from live_preview import build_live_preview_html, preview_error_document

        path = self._preview_sbs_path()
        if not path:
            self._log_queue.put(
                (
                    "line",
                    "[Preview] Select an .sbs file or a folder that contains at least one .sbs file "
                    "(folders use the first .sbs found, sorted paths).",
                )
            )
            self._apply_preview_ui(
                preview_error_document(
                    "Select an .sbs file or a folder that contains at least one .sbs file. "
                    "For folders, the first .sbs found (sorted paths) is previewed."
                ),
                "No preview source.",
                None,
            )
            return
        cfg = self._dump_config_from_ui()
        ap = self._export_selected_preset_path()
        mode = self._preview_mode()

        def preview_log(msg: str) -> None:
            self._log_queue.put(("line", f"[Preview] {msg}"))

        def work() -> None:
            try:
                preview_log(
                    f"Running {mode} preview for {os.path.basename(path)} using preset {os.path.basename(ap)}"
                )
                doc, msg = build_live_preview_html(path, cfg, ap, mode, log=preview_log)
                self.after(0, lambda d=doc, m=msg, p=path: self._apply_preview_ui(d, m, p))
            except Exception as e:
                err = str(e)
                preview_log(f"Unexpected error: {err}")
                self.after(
                    0,
                    lambda er=err, p=path: self._apply_preview_ui(preview_error_document(er), er, p),
                )

        threading.Thread(target=work, daemon=True).start()

    def _apply_preview_ui(self, html_doc: str, status_msg: str, path_hint: str | None) -> None:
        self._last_preview_html = html_doc
        mode = self._preview_mode()
        if mode.startswith("html"):
            label = "HTML (raw)" if mode.endswith("raw") else "HTML (rendered)"
        else:
            label = "Markdown (raw)" if mode.endswith("raw") else "Markdown (rendered)"
        if path_hint:
            bn = os.path.basename(path_hint)
            line = f"{bn} — {label}"
            if status_msg:
                line += f" — {status_msg}"
            self._preview_status_var.set(line)
        else:
            self._preview_status_var.set(status_msg or "")

        if self._preview_backend == "tkinterweb" and self._html_frame is not None:
            try:
                self._html_frame.load_html(html_doc)
            except Exception as e:
                self._log_queue.put(("line", f"[Preview] Display error: {e}"))
                self._preview_status_var.set(f"Preview widget error: {e}")
        elif self._html_frame is not None:
            tip = (
                "Install tkinterweb for formatted preview: pip install tkinterweb\n\n"
                if self._preview_backend == "text"
                else ""
            )
            self._html_frame.configure(state=tk.NORMAL)
            self._html_frame.delete("1.0", tk.END)
            self._html_frame.insert(tk.END, tip + html_doc[:48000])
            self._html_frame.configure(state=tk.DISABLED)

    def _open_preview_window(self) -> None:
        if not self._last_preview_html.strip():
            messagebox.showinfo("Preview", "Nothing to show yet. Select a source and wait for the preview.")
            return
        top = tk.Toplevel(self)
        top.title("Export preview")
        top.geometry("920x720")
        try:
            from tkinterweb import HtmlFrame

            hf = HtmlFrame(top, messages_enabled=False)
            hf.pack(fill=tk.BOTH, expand=True, padx=4, pady=4)
            hf.load_html(self._last_preview_html)
        except ImportError:
            tx = scrolledtext.ScrolledText(top, wrap=tk.WORD)
            tx.pack(fill=tk.BOTH, expand=True, padx=4, pady=4)
            tx.insert(
                tk.END,
                "pip install tkinterweb for formatted preview.\n\n" + self._last_preview_html[:48000],
            )

    def _append_log(self, line: str) -> None:
        self.log_widget.configure(state=tk.NORMAL)
        self.log_widget.insert(tk.END, line + "\n")
        self.log_widget.see(tk.END)
        self.log_widget.configure(state=tk.DISABLED)

    def _clear_export_links(self) -> None:
        for w in self._export_links_frame.winfo_children():
            w.destroy()

    def _populate_export_links(self, artifacts: dict[str, Any] | None) -> None:
        self._clear_export_links()
        if not artifacts:
            return
        ok_count = int(artifacts.get("ok_count") or 0)
        out_dir = str(artifacts.get("out_dir") or "")
        html_paths = list(artifacts.get("html_paths") or [])
        md_paths = list(artifacts.get("md_paths") or [])
        source_count = int(artifacts.get("source_count") or 0)

        if ok_count == 0:
            ttk.Label(
                self._export_links_frame,
                text="Last export: nothing written successfully — see log.",
                foreground="#666",
            ).pack(anchor="w")
            if out_dir and os.path.isdir(out_dir):
                ttk.Button(
                    self._export_links_frame,
                    text="Open output folder",
                    command=lambda p=out_dir: open_path_in_os(p),
                ).pack(anchor="w", pady=(4, 0))
            return

        row = ttk.Frame(self._export_links_frame)
        row.pack(fill=tk.X, anchor="w")
        ttk.Label(row, text="Open results:", font=("TkDefaultFont", 9, "bold")).pack(side=tk.LEFT)

        single_source = source_count == 1
        if single_source and html_paths:
            hp = html_paths[-1]
            ttk.Button(
                row,
                text="Exported HTML",
                command=lambda p=hp: open_path_in_os(p),
            ).pack(side=tk.LEFT, padx=(8, 0))
        elif single_source and md_paths and not html_paths:
            mp = md_paths[-1]
            ttk.Button(
                row,
                text="Exported Markdown",
                command=lambda p=mp: open_path_in_os(p),
            ).pack(side=tk.LEFT, padx=(8, 0))

        if out_dir and os.path.isdir(out_dir):
            ttk.Button(
                row,
                text="Output folder",
                command=lambda p=out_dir: open_path_in_os(p),
            ).pack(side=tk.LEFT, padx=(8, 0))

        if not single_source and out_dir:
            ttk.Label(
                self._export_links_frame,
                text="Batch: files are under category/tag subfolders inside the output folder.",
                font=("TkDefaultFont", 8),
                foreground="#444",
                wraplength=480,
            ).pack(anchor="w", pady=(4, 0))

    def _drain_log_queue(self) -> None:
        try:
            while True:
                kind, payload = self._log_queue.get_nowait()
                if kind == "line":
                    self._append_log(payload)
                elif kind == "done":
                    self.run_btn.configure(state=tk.NORMAL)
                    if isinstance(payload, dict):
                        summary = str(payload.get("summary", ""))
                        self._populate_export_links(
                            payload.get("artifacts") if isinstance(payload.get("artifacts"), dict) else None
                        )
                        messagebox.showinfo("Export finished", summary)
                    else:
                        self._populate_export_links(None)
                        messagebox.showinfo("Export finished", payload)
                elif kind == "error":
                    self.run_btn.configure(state=tk.NORMAL)
                    messagebox.showerror("Export", payload)
        except queue.Empty:
            pass
        self.after(150, self._drain_log_queue)

    def _browse_file(self) -> None:
        path = filedialog.askopenfilename(
            title="Choose .sbs file",
            filetypes=[("Substance graph", "*.sbs"), ("All files", "*.*")],
        )
        if path:
            self.source_var.set(path)

    def _browse_folder(self) -> None:
        path = filedialog.askdirectory(title="Choose folder containing .sbs files")
        if path:
            self.source_var.set(path)

    def _browse_out(self) -> None:
        path = filedialog.askdirectory(title="Output folder for HTML / Markdown")
        if path:
            self.out_var.set(path)

    def _on_run(self) -> None:
        src = self.source_var.get().strip()
        out_dir = self.out_var.get().strip()
        dump_cfg = self._dump_config_from_ui()
        save_settings(dump_config=dump_cfg.to_dict())
        write_html = self.html_var.get()
        write_md = self.md_var.get()
        recursive = self.recursive_var.get()
        autofill_path = self._export_selected_preset_path()

        if not src:
            messagebox.showwarning("Missing source", "Choose a .sbs file or folder.")
            return
        if not out_dir:
            messagebox.showwarning("Missing output", "Choose an output folder.")
            return
        if not write_html and not write_md:
            messagebox.showwarning("Nothing to export", "Enable HTML and/or Markdown.")
            return

        paths = collect_sbs_paths(src, recursive)
        if not paths:
            messagebox.showwarning(
                "No files",
                "No .sbs files found. Check the source path and subfolder option.",
            )
            return

        try:
            os.makedirs(out_dir, exist_ok=True)
        except OSError as e:
            messagebox.showerror("Output folder", str(e))
            return

        self.run_btn.configure(state=tk.DISABLED)
        self._clear_export_links()
        self.log_widget.configure(state=tk.NORMAL)
        self.log_widget.delete("1.0", tk.END)
        self.log_widget.configure(state=tk.DISABLED)

        def log_line(msg: str) -> None:
            self._log_queue.put(("line", msg))

        def work() -> None:
            log_line(f"Found {len(paths)} .sbs file(s).")
            log_line(f"Using preset: {autofill_path}")
            try:
                ok, err, artifacts = run_export(
                    paths, out_dir, dump_cfg, write_html, write_md, autofill_path, log_line
                )
                summary = f"Finished: {ok} ok, {err} failed or skipped.\nOutput: {out_dir}"
                self._log_queue.put(
                    ("done", {"summary": summary, "artifacts": artifacts})
                )
            except Exception as e:
                log_line(f"Export failed: {e}")
                self._log_queue.put(("error", str(e)))

        self._worker = threading.Thread(target=work, daemon=True)
        self._worker.start()


def main() -> None:
    app = SBSParamDumperApp()
    app.mainloop()


if __name__ == "__main__":
    main()
